### ISSUE TITLE
Support Apple M1

### ISSUE THREAD

**Issue by sobrinho** [qltysh/codeclimate#1030] opened 2021-09-08 21:14 UTC
```
$ docker run \                                                                                       host Gabriels-MacBook-Air  pwd jobs  vcs intg-1505  ruby 2.7.2  node 14.15.4
  --interactive --tty --rm \
  --env CODECLIMATE_CODE="$PWD" \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  codeclimate/codeclimate help
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Usage: codeclimate COMMAND ...

Available commands:
    analyze [-f format] [-e engine[:channel]] [path]    Run analysis with the given arguments
    console                                             Open a ruby console for the CLI. Useful for developing against the CLI.
    engines:install                                     Pull the latest images for enabled engines in your configuration
    engines:list                                        List all available engines
    help [command]                                      Display help information.
    prepare [--allow-internal-ips]                      Run the commands in your prepare step.
    validate-config                                     Validate your .codeclimate.yml or .codeclimate.json.
    version                                             Display the CLI version.
```

**Comment by MikeBenza** [comment] 2021-12-22 19:20
It looks like it runs, just with a warning:

```
docker run \                                                                                                                                        9s  13:13:39
  --interactive --tty --rm \
  --env CODECLIMATE_CODE="$PWD" \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  codeclimate/codeclimate analyze
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Starting analysis
Running structure: Done!
Running duplication: Done!

Analysis complete! Found 0 issues.
```

**Comment by gondalez** [comment] 2022-01-10 08:51
For the project I work on I can confirm using [`codeclimate/codeclimate`](https://hub.docker.com/r/codeclimate/codeclimate) is a lot slower on an m1 machine under emulation.

I have left it running for > 20 minutes without it finishing and I can see qemu working away: 
![image](https://user-images.githubusercontent.com/1468141/148739099-292f1aa4-903b-4edb-a518-ec684885839e.png)

So I can't really use it at the moment to run quick local checks.
Previously it would finish in tens of seconds. 

A multi-arch docker image with multi-arch support might make this usable on m1 🙏❤️🍎

**Comment by johngallagher** [comment] 2022-01-25 14:55
I too have this problem. I'm waiting a long time for Code Climate to complete on the hosted version and want to run some quick checks locally to save myself development time, but running the command locally takes way too long.

Is there any way of building from source to get a performance improvement?

**Comment by aflansburg** [comment] 2022-04-27 13:47
+1 for incredibly long runtime on M1 - also 👀  for some way to build from source for quicker runtime

**Comment by brynary** [comment] 2024-11-15 23:39
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.

**Closed by brynary** 2024-11-15 23:39 UTC
