### ISSUE TITLE
Very slow initialization of `codeclimate analyze` unless all `node_modules` directories are not made available to Docker

### ISSUE THREAD

**Issue by jonahwh** [qltysh/codeclimate#912] opened 2019-04-19 18:34 UTC
This seems similar to https://github.com/codeclimate/codeclimate/issues/238

When running `codeclimate analyze` (or just directly invoking docker) in a project with any `node_modules` folders, the command hangs for a while (usually in my case, just over 30 seconds) before actually starting analysis. 

If we do any of the following, the analysis runs as speedily as expected:
* Remove all `node_modules` folder in the project
* Remove Read access from all `node_modules` folders
* Mount empty directories to the `node_modules` folder, via docker flags, e.g.

```bash
docker run \
  --rm \
  --env CODECLIMATE_CODE="$PWD" \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  # this is the magic flag that "fixes" the issue
  --volume /code/node_modules \
  codeclimate/codeclimate analyze)
```

`- "**/node_modules/"` is in our `exclude_patterns` setting in `.codeclimate.yml`, and even if we wait for codeclimate to start with all the `node_modules` folders intact, the engines don't run on them, but it seems the excluded files are still being scanned before any engines start up.

Some output:
### Without cleaning up `node_modules`
```
 ❯ docker run \
  --rm \
  --env CODECLIMATE_CODE="$PWD" \
  --env CODECLIMATE_DEBUG \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  codeclimate/codeclimate analyze
I, [2019-04-19T18:32:50.980276 #1]  INFO -- : starting engine structure
D, [2019-04-19T18:33:27.439929 #1] DEBUG -- : /config.json content:
```
~37 seconds

### With cleaning up `node_modules` by any method mentioned above
```
❯ docker run \
  --rm \
  --env CODECLIMATE_CODE="$PWD" \
  --env CODECLIMATE_DEBUG \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  --volume /code/node_modules \
  codeclimate/codeclimate analyze
I, [2019-04-19T18:26:12.105992 #1]  INFO -- : starting engine structure
D, [2019-04-19T18:26:12.263300 #1] DEBUG -- : /config.json content: 
```
<1 second

**Comment by wfleming** [comment] 2019-04-20 15:01
Hi @jonahwh, can you please share the contents of your `.codeclimate.yml`? It would be helpful to see all of your exclude patterns to be able to better understand what might be causing this issue.

**Comment by jonahwh** [comment] 2019-04-20 16:38
```
version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
plugins:
  duplication:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-5"
exclude_paths:
  - "app/build"
  - "**/node_modules/"
  - "**/generated/"
  - "app/src/serviceWorker.ts"
```

**Comment by wfleming** [comment] 2019-05-22 21:07
@jonahwh apologies for my very delayed reply here, I haven't had much time to look at this.

Unfortunately I'm having trouble reproducing this. I do have one shot-in-the-dark suggestion: instead of using `**/node_modules` in your pattern, could you just exclude `node_modules/`? (Or if you have several `node_modules` directories you're trying to exclude, could you list each of them explicitly without using wildcards?)

The reason I suggest this is that if you have a particularly large/deep `node_modules` directory, globbing for `**/node_modules` means Ruby's `Dir.glob` will walk the entire directory structure of your project looking for `node_modules`, and if your project is particularly large or your `node_modules` install is particularly large, that's wasted time. Our CLI processes exclude patterns by [using Ruby stdlib's `Dir.glob`](https://github.com/codeclimate/codeclimate/blob/master/lib/cc/workspace/exclusion.rb#L11) to expand the patterns fully and then exclud the matches, so on large projects `**` can slow down processing exclusions, although your case is unusually slow.

That being said, 30 secs to walk a directory tree would have to be a very, very large directory tree. So if that doesn't help, I'd like to ask a few follow up questions.

- I presume the project you're working on is private, but would it be possible for you to share a modified version of your `package.json` (with project details removed but the same dependencies) to help me try and reproduce the slowness?
- What operating system are you using? If MacOS, are you using Docker for Mac, and if so what version? (Docker for Mac's filesystem handling has some [significant performance issues](https://docs.docker.com/docker-for-mac/osxfs/#performance-issues-solutions-and-roadmap in certain cases))

**Comment by zharikovpro** [comment] 2019-12-14 15:22
I have faced the same issue. For somewhat reason, global exclusion pattern didn't help to deal with node_modules. The workaround is to add explicit paths for duplication engine:

```
version: "2"
exclude_patterns:
  - "**/node_modules/"
  - "**/vendor/"
  - "**/app/locales/"
  - "**/db/schema.rb"
  duplication:
    enabled: true
    exclude_patterns:
      # global config is not enough for somewhat reason
      # list each nodes_modules path separately, to speed up local analyzes
      - "frontend/smhw-frontend/node_modules/"
      - "frontend/smhw-frontend/bower_components/"
      - "frontend/admin-frontend/node_modules/"
      - "frontend/admin-frontend/bower_components/"
```

**Comment by satanTime** [comment] 2020-11-02 19:15
The same here. I have a lot of node_modules directories with millions of files excluded in the config, but looks like the tools still goes into node_modules directories and scans them.

```yaml
version: '2'
exclude_patterns:
  - 'dist/'
  - 'e2e/'
  - 'examples/'
  - 'node_modules/'
  - 'test-reports/'
  - 'tests/'
  - 'tmp/'
  - '**/*.spec.ts'
  - '**/*.fixtures.ts'
plugins:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
```

under `e2e` I have a lot of files locally. Once I delete all the files the tool runs very fast.

**Comment by brynary** [comment] 2024-11-15 23:42
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.

**Closed by brynary** 2024-11-15 23:42 UTC
