### ISSUE TITLE
Update cppcheck engine Docker container

### ISSUE THREAD

**Issue by kjerstadius** [qltysh/codeclimate#920] opened 2019-07-11 11:06 UTC
Hi,

First of all, I'm sorry if this isn't the right place to raise this issue, but I found it a bit unclear as to where this type of request actually belongs. If it belongs somewhere else, please let me know and I'll raise it there. Anyway...

The cppcheck engine [has been updated recently](https://github.com/antiagainst/codeclimate-cppcheck/commits/master) (most importantly IMO, it's now using cppcheck 1.87), but the Docker image over at Docker Hub hasn't yet been updated. Therefore I'd like to request that the official image gets updated.

Thanks

**Comment by kate-grechishkina** [comment] 2021-03-26 18:19
It seems like a duplicate of [this](https://github.com/codeclimate/codeclimate/issues/989) issue, but it is also left without response.

**Comment by brynary** [comment] 2024-11-15 23:42
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.

**Closed by brynary** 2024-11-15 23:42 UTC
