### ISSUE TITLE
Fail with Error Code if Analysis Engine Finds Issues?

### ISSUE THREAD

**Issue by joncursi** [qltysh/codeclimate#422] opened 2016-05-05 16:44 UTC
If the analysis engine finds issues with your code, no error code is returned. The results are printed to console and the process is marked as a success. This makes it impossible to bake CodeClimate CLI into automated workflows that listen for such failures (aka when things "break").

**Comment by pbrisbin** [comment] 2016-05-05 16:48
I'm genuinely surprised by this, but have confirmed that's what's happening. This was either an oversight or a regression; either way, we'll look to fix soon. Thanks!

**Comment by joncursi** [comment] 2017-02-14 03:50
@pbrisbin is this still on the roadmap?

**Comment by pbrisbin** [comment] 2017-02-14 19:16
Hi @joncursi, sorry I was a little over-eager with my use of "soon" previously. We agree this is an issue, but we have no concrete plans to work on it quite yet.

**Comment by devth** [comment] 2017-03-06 23:57
I'm interested in this issue and potentially helping out.

1. isn't this contradictory to the [spec](https://github.com/codeclimate/spec/blob/master/SPEC.md#output)?
2. why was https://github.com/codeclimate/codeclimate/pull/508 closed?

**Comment by pbrisbin** [comment] 2017-03-07 00:33
Hey @devth thanks for offering to take a swing at this!

1. This doesn't contradict the SPEC. The SPEC is referring to engines themselves, which should not exit non-zero when they find issues; the behavior of the CLI is not part of the SPEC
1. That PR just got stale. It looks like there were some open discussion threads but, as is usually the case with stale PRs, I don't really remember the specifics

**Comment by devth** [comment] 2017-05-10 13:49
I think individual engines should be allowed to fail based on config. For example:

```yaml
engines:
  markdownlint:
    enabled: true
  fixme:
    enabled: true
    allow_failure: true
  shellcheck:
    enabled: true
```

In this case `allow_failure: true` is set on the `fixme` engine. Reasoning is that it can be useful to see those issues in the build log, but I don't want to fail the build because of them.

The default would be `allow_failure: false` meaning if any issues were found for an engine then `analyze` would `exit 1`.

Thoughts?

**Comment by pbrisbin** [comment] 2017-05-10 14:24
That seems like a worthwhile extension, but I would suggest doing it separately. Personally, I think exiting non-zero when issues are found is a saner default which could be implemented separate from, and before having the option to turn it off engine-by-engine.

I could be convinced that a global flag to go back to the old behavior would be useful so we don't just start erroring folks' builds, but engine-by-engine seems like clear feature-creep that can be tackled after.

**Comment by dahlb** [comment] 2017-11-16 23:48
in the mean time the work around I am using is to pipe the results into a file then grep the file as grep will return 0 or 1 for matches
ie:

analyze -f json > codeclimate.json
cat codeclimate.json
grep "^\[\]$" codeclimate.json

**Comment by wfleming** [comment] 2018-04-28 00:03
Hi @jkugler thanks for your interest in helping out. I'm going to ask @chrishulton to give his thoughts here since he works a bit more closely with the CLI codebase than I do these days, but I'll try and sketch out my own thoughts on what I think an appropriate way to implement this support would be.

1. Any direct calls to `exit` should probably be limited to the [command class under `CC::CLI`](https://github.com/codeclimate/codeclimate/blob/master/lib/cc/cli/analyze.rb), or something in that area. Code under `CC::Analyzer` (where you'll find formatter-related code) is treated like a functional library reused in non-CLI contexts where hard-exits would be problematic.
2. The exit code for these states should probably not be `1`. Since `1` is generally the "who knows what just happened" error code for unix CLI tools, and is already the exit code the CLI uses when it crashes for any reason, I think it's important for scripting purposes that the exit code for "we found issues with your code" be different from "the CLI crashed". So for the sake of expediency let's say the exit code for this should probably be `2`.
3. I suspect the [`text`](https://github.com/codeclimate/codeclimate/blob/master/lib/cc/analyzer/formatters/plain_text_formatter.rb) (default) formatter might be the only specific formatter that it's appropriate to have this exit code apply to? My thinking is that the text formatter seems likely to be the one that people will use in CI/scripting environments where you would in fact want to be likely to error/exit immediately if issues were found. Exiting with this error code on, for example, the JSON formatter doesn't make much sense to me since most shell scripts are going to have `set -e` (I hope), and the main reason for using the JSON formatter is to collect the JSON issue details in order to do something with those JSON issues later in the same script, so `set -e` combined with a non-zero exit code would be likely to break existing scripts.

To sum up, I suspect the best first pass is:

- [`Formatter` base class's](https://github.com/codeclimate/codeclimate/blob/master/lib/cc/analyzer/formatters/formatter.rb) interface should expand to return some details about 1) did it output any issues and 2) is it a kind of formatter that should exit with a nonzero exit code if it did.
- The [`PlainTextFormatter`](https://github.com/codeclimate/codeclimate/blob/master/lib/cc/analyzer/formatters/plain_text_formatter.rb) should implement that new interface appropriately.
- The [`Analyze` command](https://github.com/codeclimate/codeclimate/blob/master/lib/cc/cli/analyze.rb) should learn to use that new interface, and exit with an appropriate code if necessary.

Let me know if that makes sense to you, and @chrishulton please let chime in here with your thoughts on the subject.

**Comment by brynary** [comment] 2024-11-15 23:44
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.

**Closed by brynary** 2024-11-15 23:44 UTC
Labels: bug, help wanted, hacktoberfest
